export const UserType = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT'
};

export const OfferType = {
  SELECTED_OFFER: 'SELECTED_OFFER',
  CLEAR_OFFER: 'CLEAR_OFFER'
};

export const buyerOfferType = {
  SET_BUYER_AMOUNT: 'SET_BUYER_AMOUNT',
  SET_ESCROW_FEE: 'SET_ESCROW_FEE',
  SET_COIN_AMOUNT: 'SET_COIN_AMOUNT',
  RESET_OFFER: 'RESET_OFFER'
}

export const TradeInfoType = {
  SET_TRADE_INFO: 'SET_TRADE_INFO',
  CLEAR_TRADE_INFO: 'CLEAR_TRADE_INFO'
};

export const CoinsType = {
  FETCH_COINS: 'FETCH_COINS',
  SET_COINS: 'SET_COINS',
  FETCH_COINS_FAILED: 'FETCH_COINS_FAILED'
};